# Generated by Django 4.2.3 on 2023-10-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0008_accessfailurelog'),
        ('transaction_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttemptAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Time')),
                ('accessattempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='axes.accessattempt')),
            ],
        ),
    ]
