# Generated by Django 4.2.3 on 2023-10-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0005_remove_accessattempt_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessattempt',
            old_name='userattempt',
            new_name='user',
        ),
    ]
