# Generated by Django 4.2.3 on 2023-10-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0006_rename_userattempt_accessattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
